Numpy: Numerical python. It is a linear algebra library for python, the reason it is so imp for data science with python.

installation : pip install numpy

Numpy arrays essentially come in 2 flavor: vector means 1d array and matrices means 2d array

In [1]:
import numpy as np

In [2]:
my_lits=[1,2,3]
arr = np.array(my_lits)
arr

array([1, 2, 3])

In [3]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

creating a random numbers numpy array

In [4]:
np.arange(0,10) # arange function is same as range function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)


array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.linspace(0,20,10) # in linspace 3 number works like total number you want to print between the specified range

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [16]:
np.eye(4) # eye function is used to print the identity element

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.66917948, 0.11573884, 0.65389605, 0.66791072, 0.2423298 ])

In [19]:
np.random.rand(5,5)

array([[0.86140251, 0.74672291, 0.32542887, 0.40564664, 0.43289695],
       [0.24209514, 0.98447094, 0.13059308, 0.49173168, 0.71294458],
       [0.11504561, 0.89287578, 0.6120902 , 0.31452144, 0.37017924],
       [0.65653202, 0.5045151 , 0.5507764 , 0.68266832, 0.32833953],
       [0.6449768 , 0.11311458, 0.70754082, 0.39263827, 0.58400956]])

In [26]:
r = np.random.randint(0,10,(2,3))
r

array([[5, 8, 9],
       [7, 6, 6]])

In [27]:
r.max()

9

In [28]:
r.reshape(3,2)

array([[5, 8],
       [9, 7],
       [6, 6]])

In [29]:
r.min()

5

In [30]:
r.argmax()# this will print the index number of maximum value

2

# Numpy Indexing And Selection

In [32]:
ar = np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
ar.dtype

dtype('int32')

In [37]:
ar[8] # it will the 8 index value

8

In [38]:
ar[1:5]

array([1, 2, 3, 4])

In [40]:
ar[0:5]=10 # here we are changing the value from 0 index to 4 index with 10
ar

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [43]:
arr = np.array([[2,10,15],[20,25,30],[35,40,45]])
arr

array([[ 2, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
arr[0]

array([ 2, 10, 15])

In [45]:
# print 30 from arr
arr[1][2]

30

In [46]:
arr[1,2]

30

# Numpy Operations
- Array with array
- Array with Scalars
- Universal Array Functions

In [47]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- adding array with array

In [48]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [49]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

adding array with scalar 
scalr means random number

In [51]:
arr + 2 # it will add 2 with every element in an array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
arr *10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [53]:
arr / arr  # in this if there is 0 in an array then it will given an error because 0/0 give zerodivision error in python in place of 0/0 it will print nan the whole code will run but error will also be shown.

C:\Users\anuku\AppData\Local\Temp\ipykernel_2152\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# Exercise :

Import numpy

In [54]:
import numpy as np

Create an array of 10 zeros 

In [55]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of 10 ones

In [56]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives

In [57]:
a = np.ones(10)
a*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create an array of the integers from 10 to 50

In [58]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create an array of all the even integers from 10 to 50

In [60]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

Create a 3x3 matrix with values ranging from 0 to 8

In [70]:
a = np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create 3*3 identity matrix

In [71]:
# to create identity matrix we use eye function
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use numpy to generate a random number between 0 and 1

In [81]:
np.random.rand(1)

array([0.58132276])

Generate an array of 25 random numbers

In [83]:
np.random.randn(25)

array([ 1.51814327, -0.42793531, -0.60767031,  0.07070662,  0.45437613,
        1.31273489,  0.1819571 , -0.2683192 ,  0.84426127, -0.36975556,
       -0.57613398,  1.32054813,  0.55725624, -0.65927219,  0.42606861,
        0.20810683,  0.57716946,  1.8032091 , -0.46595091, -0.96779832,
       -0.18937516,  0.49790978,  1.48841764, -1.82309715,  0.60685116])

In [87]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [88]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [89]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

print : 12,13,14,15
        17,18,19,20
        22,23,24,25 from mat variable

In [90]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

print 20 from mat variable

In [91]:
mat[3][4]

20

print : array([[ 2],
               [ 7],
               [12]])

In [92]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [94]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

print : array([21, 22, 23, 24, 25])

In [95]:
mat[-1,:]

array([21, 22, 23, 24, 25])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [96]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [97]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [98]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [104]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])