Numpy: Numerical python. It is a linear algebra library for python, the reason it is so imp for data science with python.

installation : pip install numpy

Numpy arrays essentially come in 2 flavor: vector means 1d array and matrices means 2d array

In [1]:
import numpy as np

In [2]:
my_lits=[1,2,3]
arr = np.array(my_lits)
arr

array([1, 2, 3])

In [3]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

creating a random numbers numpy array

In [4]:
np.arange(0,10) # arange function is same as range function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.linspace(0,20,10) # in linspace 3 number works like total number you want to print between the specified range

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [9]:
np.eye(4) # eye function is used to print the identity element

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.rand(5)

array([0.23642411, 0.95984325, 0.92602543, 0.94128774, 0.78866622])

In [11]:
np.random.rand(5,5)

array([[0.97462844, 0.22824142, 0.83061326, 0.71386649, 0.38489265],
       [0.00889366, 0.2102012 , 0.23483743, 0.21690938, 0.28434615],
       [0.85605164, 0.27368308, 0.32451136, 0.23683523, 0.69665588],
       [0.82426629, 0.31487509, 0.79376769, 0.33189591, 0.45927162],
       [0.14789468, 0.96599879, 0.95181837, 0.39911795, 0.71251543]])

In [12]:
r = np.random.randint(0,10,(2,3))
r

array([[0, 2, 3],
       [1, 5, 0]])

In [13]:
r.max()

5

In [14]:
r.reshape(3,2)

array([[0, 2],
       [3, 1],
       [5, 0]])

In [15]:
r.min()

0

In [16]:
r.argmax()# this will print the index number of maximum value

4

# Numpy Indexing And Selection

In [17]:
ar = np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
ar.dtype

dtype('int32')

In [19]:
ar[8] # it will the 8 index value

8

In [20]:
ar[1:5]

array([1, 2, 3, 4])

In [21]:
ar[0:5]=10 # here we are changing the value from 0 index to 4 index with 10
ar

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [22]:
arr = np.array([[2,10,15],[20,25,30],[35,40,45]])
arr

array([[ 2, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr[0]

array([ 2, 10, 15])

In [24]:
# print 30 from arr
arr[1][2]

30

In [25]:
arr[1,2]

30

# Numpy Operations
- Array with array
- Array with Scalars
- Universal Array Functions

In [26]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- adding array with array

In [27]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

adding array with scalar 
scalr means random number

In [29]:
arr + 2 # it will add 2 with every element in an array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
arr *10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [31]:
arr / arr  # in this if there is 0 in an array then it will given an error because 0/0 give zerodivision error in python in place of 0/0 it will print nan the whole code will run but error will also be shown.

C:\Users\anuku\AppData\Local\Temp\ipykernel_22476\1433951870.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr  # in this if there is 0 in an array then it will given an error because 0/0 give zerodivision error in python in place of 0/0 it will print nan the whole code will run but error will also be shown.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# Exercise :

Import numpy

In [32]:
import numpy as np

Create an array of 10 zeros 

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of 10 ones

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives

In [35]:
a = np.ones(10)
a*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create an array of the integers from 10 to 50

In [36]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create an array of all the even integers from 10 to 50

In [37]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

Create a 3x3 matrix with values ranging from 0 to 8

In [38]:
a = np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create 3*3 identity matrix

In [5]:
# to create identity matrix we use eye function
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use numpy to generate a random number between 0 and 1

In [40]:
np.random.rand(1)

array([0.24434597])

Generate an array of 25 random numbers

In [41]:
np.random.randn(25)

array([-0.7857448 , -0.97869851,  2.20190059,  0.10585506,  1.17446191,
        0.36198938,  0.56424393,  0.89370616,  0.38299313, -0.67254689,
       -0.74259678, -2.30614189, -1.20057035, -2.76873926, -0.5719576 ,
       -0.34626012,  0.05931576,  0.04226719,  1.08851775, -0.94038832,
        1.39161139,  2.2776286 ,  1.17883752, -0.1025435 , -0.89661632])

In [42]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [6]:
np.linspace(0,1,20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [44]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

print : 12,13,14,15
        17,18,19,20
        22,23,24,25 from mat variable

In [45]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

print 20 from mat variable

In [46]:
mat[3][4]

20

print : array([[ 2],
               [ 7],
               [12]])

In [47]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [48]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

print : array([21, 22, 23, 24, 25])

In [49]:
mat[-1,:]

array([21, 22, 23, 24, 25])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [50]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [51]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [52]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [53]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])