# Decision Tree Concept

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
%matplotlib inline

In [5]:
df = pd.read_csv('Salary.csv')

In [6]:
df.head()

company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   company                16 non-null     object
 1   job                    16 non-null     object
 2   degree                 16 non-null     object
 3   salary_more_then_100k  16 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 640.0+ bytes


In [8]:
df.describe()

salary_more_then_100k
count                 16.000
mean                   0.625
std                    0.500
min                    0.000
25%                    0.000
50%                    1.000
75%                    1.000
max                    1.000

### use labelEncoder to change the object type to integer. 
#### labelEncoder automatically change to integer type..

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [11]:
df['n_company'] = le_company.fit_transform(df['company'])
df['n_job'] = le_job.fit_transform(df['job'])
df['n_degree'] = le_degree.fit_transform(df['degree'])

In [12]:
df.head()

company                  job     degree  salary_more_then_100k  n_company  \
0  google      sales executive  bachelors                      0          2   
1  google      sales executive    masters                      0          2   
2  google     business manager  bachelors                      1          2   
3  google     business manager    masters                      1          2   
4  google  computer programmer  bachelors                      0          2   

   n_job  n_degree  
0      2         0  
1      2         1  
2      0         0  
3      0         1  
4      1         0

In [13]:
column = ['company','job','degree']
df.drop(columns=column,axis=1,inplace=True)

In [14]:
df.head()

salary_more_then_100k  n_company  n_job  n_degree
0                      0          2      2         0
1                      0          2      2         1
2                      1          2      0         0
3                      1          2      0         1
4                      0          2      1         0

# Train the model

In [15]:
X = df[['n_company','n_job','n_degree']]
Y = df['salary_more_then_100k']

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [18]:
from sklearn import tree

In [19]:
model = tree.DecisionTreeClassifier()

In [20]:
# model.fit(X,Y)

In [21]:
model.fit(X_train,Y_train)

In [22]:
model.score(X_train,Y_train) #finding the accuracy of the model

1.0

## Is salary of Google, Computer Engineer, Bachelors degree > 100 k ?
- Answer is no

In [23]:
model.predict([[2,1,0]])

c:\Users\anuku\miniconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

Is salary of Google, Computer Engineer, Masters degree > 100 k ?


In [24]:
model.predict([[2,1,1]])

c:\Users\anuku\miniconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [25]:
prediction = model.predict(X_test)

In [26]:
prediction

array([1, 0, 0, 0], dtype=int64)

In [27]:
from sklearn.metrics import classification_report

In [28]:
print(classification_report(Y_test,prediction))

              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.00      0.00      0.00         1

    accuracy                           0.50         4
   macro avg       0.33      0.33      0.33         4
weighted avg       0.50      0.50      0.50         4

